# Generated by Django 6.0.7 on 2026-07-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Samwa Bakery', max_length=200)),
                ('location', models.CharField(default='Mvurwi, Mashonaland Central', help_text='Town/area shown in page titles and meta description.', max_length=200)),
                ('whatsapp_number', models.CharField(help_text='Format: +263712345678 (include the country code).', max_length=20)),
                ('address', models.TextField(help_text='Full street address shown in the footer.')),
                ('opening_hours', models.TextField(help_text='One rule per line, e.g.:\nMon-Fri: 07:00-18:00\nSat-Sun: 08:00-16:00')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('brand_color', models.CharField(default='#d97706', help_text='Hex color used for buttons/accents, e.g. #d97706.', max_length=7)),
            ],
            options={
                'verbose_name': 'Bakery Info',
                'verbose_name_plural': 'Bakery Info',
            },
        ),
    ]
